name-template: '$NEXT_MINOR_VERSION'
tag-template: '$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🔥 Hot Fixes'
    labels:
      - 'hotfix'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
      - 'maintain'
  - title: '👮 Security'
    label: 'security'
  - title: '🤖 Dependabot'
    label: 'dependencies'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
