nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

supportedArchitectures:
  cpu:
    - current
    - x64
    - x86
    - arm
    - ia32
  libc:
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-3.6.3.cjs
