name: Slacktion
description: Action used to send messages to slack via a webhook.
author: '@zrosenbauer'
inputs:
  username:
    description: Use to specify the username for the published message.
    required: false
  text:
    description: Use to define the message that will be sent to slack.
    required: true
  webhook_url:
    description: Use to define the webhook URL used to send a message.
    required: true
  icon_emoji:
    description: Use to specify an emoji (using colon shortcodes, eg. :white_check_mark:) to use as the profile photo alongside the message.
    required: false
  icon_url:
    description: Use to specify a URL to an image to use as the profile photo alongside the message.
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: mail
  color: blue
