name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lintAndTest:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Packages
        run: yarn install
      - name: Format Check
        run: yarn format-check
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - id: runAction
        name: Run Action Code
        uses: ./
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: This is a new commit - ${{ github.sha }}
          username: "BlueNova Bot"
          icon_url: "https://raw.githubusercontent.com/bluenovaio/action-slack/main/bluenova-icon.png?token=AA2TF7NCV2CT7AOSJ5IPDJTAIW4HG"
